### ISSUE TITLE
Issue while retrieving Child Folders

### ISSUE THREAD

**Issue by sonia1234** [Penneo/sdk-net#72]
I always get null value while trying to retrieve folders child folders, seems like ChildFolders property doesn't working.
Query.Find<Folder>(folderId).ChildFolders.

**Comment by ahmadnazir** [comment]
This is related to Penneo's REST API rather than the SDK. If a specific folder is fetched, only the parent is included in the response.

You can only access the child folders if all the folders are fetched i.e.

```
Query.FindAll();
```

I know that this can be bad for performance so we are going to introduce a way to fetch the children using another endpoint and you'll be able to call it using a raw API call. Keep an eye on #57.
